### ISSUE TITLE
project whitelist DIRENV_ALLOW

### ISSUE THREAD

**Issue by JeanMertz** [direnv/direnv#180]
I found an [issue](https://github.com/direnv/direnv/issues/23) discussing a `DIRENV_ALLOW` whitelist path to allow all `.envrc` files inside that path.

It doesn't look like this was ever implemented. We're using Direnv heavily in our project, with each directory having a different set of env vars being set. However, having to allow each file every time a developer makes a change is becoming cumbersome.

In general, we trust the developers working on this project, so it would make sense to whitelist all direnv files in this repository.

Is there a way to do this? Or are there some ideas to add this feaure?

**Comment by JeanMertz** [comment]
Also: symlinking to an existing (and allowed) direnv still wants you to allow the symlink, even though its contents are already alowed somewhere else. Is this a bug?

**Comment by zimbatm** [comment]
Hi @JeanMertz ,

I'm not against adding a `DIRENV_ALLOW` setting, just never took the time to implement it. Do you want to give it a shot ? The auth logic is contained in the `rc.go` file.

Since that ticket I've been convinced to also make the path as part of the hash so two identical files can have different hashes. The reason is that an innocuous-looking file can be devastating in a different context. I know it's a bit paranoid but it's also good for security.

**Comment by zimbatm** [comment]
Fixed in master!

**Comment by JeanMertz** [comment]
Wow, sorry for not commenting on this in the last couple of years 🙈 nice to see this being implemented, awesome 👍

**Comment by zimbatm** [comment]
no worries. I just released https://github.com/direnv/direnv/releases/tag/v2.15.0 that contains this feature

**Comment by ssbarnea** [comment]
@zimbatm Apparently this feature does not work on version 2.16.0 on Linux, even after setting this to `.bash_profile`:

```

export DIRENV_ALLOW=$HOME
eval "$(direnv hook bash)"
```

I checked and the environment variable is set but when I cd to a a subfolder which contains the .envrc, I still get:
```
direnv: error .envrc is blocked. Run `direnv allow` to approve its content.
```
Running manually `direnv allow` would be useless as these .envrc files are generate during build and the who point was to auto load them when the user is switching to the build folder.

Still, I used the same feature on MacOS without problems. 

Also this feature is too important to be missed from mentioned when doing "direnv help".

**Comment by LaurensRietveld** [comment]
Correction to post above, path should be `$HOME/.config/direnv/config.toml` (this bit me for a while ;) )

**Comment by zimbatm** [comment]
thanks, updated the example

**Comment by zimbatm** [comment]
hmm, it looks like the documentation has been wrong all these years as well.
