### ISSUE TITLE
Feature Request: Externalise .envrc file out of the project dir 

### ISSUE THREAD

**Issue by stephencheng** [direnv/direnv#385]
## Issue description
Sometimes, the envrc contains sensitive/personlised information that people do not want to put it into git repo or declare it in .gitignore

In such a case, I'd like a feature that there is a way the .envrc could be store outside of project folder. This enables it to be more like a configuration management tool.

## Technical details
The implementation could be:
1. add a key entry for project directory
2. add the file path of .envrc/or allow whatever file name is to be associated with the key entry

Thanks

**Comment by dewrich** [comment]
Why not just use the default shell profile?  Or a custom .myenvrc

**Comment by kaukas** [comment]
Another option is to "git ignore" `.envrc`s globaly perhaps?

**Comment by zimbatm** [comment]
Yes, a common solution is to set the global git config to ignore the `.envrc` as described in https://github.com/direnv/direnv/wiki/Git

**Comment by Nadrieril** [comment]
I'd quite like this feature too. My usecase is that when I work on a project I often need a project-specific nix shell, but if the project is not mine I can't add a `.envrc` to it. The solution to globally gitignore `.envrc` doesn't work, because I do have projects where I want to commit the `.envrc`. And I'd like to avoid needing to put anything in the project directory that I might commit by mistake

**Comment by stephencheng** [comment]
Hi guys

just a quick update on this

I have got a static way to config env vars and I have published a tool for it: https://github.com/upcmd/up

some examples:

- https://upcmd.netlify.app/env-vars/c0046/
- https://upcmd.netlify.app/env-vars/c0193/
- https://upcmd.netlify.app/env-vars/c0048/

Initially, I was hoping there could be some sort of integration with direnv but I am not entirely sure how the shell function could be managed in the golang code base, maybe @zimbatm could comment on it. I wish there could be a cmd support in my tool to dynamically load and unload the entire envrc context

@Nadrieril see if this could help you

**Comment by Nadrieril** [comment]
I want something directory-specific but I don't see where your tool does that

**Comment by stephencheng** [comment]
> I want something directory-specific but I don't see where your tool does that

Ref to: 
- https://upcmd.netlify.app/usage/cli_args/
- https://upcmd.netlify.app/usage/config_yml/

So basically you could load both upconfig.yml as config file and up.yml as env/workflow/var config externally using command line args

@Nadrieril Let me know your case if you need help, I can help you with a prototype usage

**Comment by Nadrieril** [comment]
I have read this doc and I am still not understanding. Maybe we didn't understand each other. But anyways, I don't want to use this powerful tool for a simple task that direnv does well already.
I appreciate the offer but I find it out of scope for this issue

**Comment by zimbatm** [comment]
@stephencheng this seems to be a bit out of topic. How I see it, implementing this feature is would require changing the internals of direnv.

There are two possible roads for this ticket (which are complementary):

* Extend the heuristic to support more file types than .envrc. This would allow to not have to create `.envrc` files for all projects. See for example #284 
* Add a second layer of storage outside of the folder. For example `direnv edit --private .` could create a file at `.config/direnv/envrcs/<dir-hash>`. And then the loading heuristic would also have to look at that place.

**Comment by Nadrieril** [comment]
Either would solve the problem for me! A variant of the first option would be to add a config option to tell direnv which files to read, eg both `.envrc` and `.envrc-private`. One could then globally gitignore `.envrc-private`, and have the `.envrc` still work for repos that track them.

**Comment by stephencheng** [comment]
> @stephencheng this seems to be a bit out of topic. How I see it, implementing this feature is would require changing the internals of direnv.
> 
> There are two possible roads for this ticket (which are complementary):
> 
> * Extend the heuristic to support more file types than .envrc. This would allow to not have to create `.envrc` files for all projects. See for example #284
> * Add a second layer of storage outside of the folder. For example `direnv edit --private .` could create a file at `.config/direnv/envrcs/<dir-hash>`. And then the loading heuristic would also have to look at that place.

I think currently it might be just GOOD to use the static configuration in UPcmd, as it is intended mainly to be working with CI/CD, it has already got the mechanism to load them with a few different options. So "explicit" during execution time would be the main use case and it also avoids polluting the execution context and increase the complexity of implementation and causing bugs.

Thanks anyway

**Comment by stephencheng** [comment]
> Either would solve the problem for me! A variant of the first option would be to add a config option to tell direnv which files to read, eg both `.envrc` and `.envrc-private`. One could then globally gitignore `.envrc-private`, and have the `.envrc` still work for repos that track them.

Not to try to sell it. I think the line for me to draw is: if I use the interactive shell session to run my local test, I intend to use direnv more, but if I set it up for CI/CD pipeline(in case I need to load a pure/clean env vars, or more complicated scenarios to snapshot/restore to a point of time), I will use UPcmd

I have come out a simple example to show how to use it:
https://github.com/upcmd/up/blob/master/tests/functests/c0208.yml

```
loading [Config]:  ./tests/functests/upconfig.yml
Main config:
             Version -> 1.0.0
              RefDir -> ./tests/functests
             WorkDir -> cwd
          AbsWorkDir -> /up-project/up
            TaskFile -> wip.yml
             Verbose -> v
          ModuleName -> self
           ShellType -> /bin/sh
       MaxCallLayers -> 8
             Timeout -> 3600000
 MaxModuelCallLayers -> 256
           EntryTask -> task
  ModRepoUsernameRef -> 
  ModRepoPasswordRef -> 
work dir: /up-project/up
-exec task: task
loading [Task]:  ./tests/functests/wip.yml
module: [self], instance id: [dev], exec profile: []
Task1: [task ==> task:  ]
-Step1: [
a alternative solution for https://github.com/direnv/direnv/issues/385
compared to using .envrc, which loads the env vars into current shell exec context, this
will load the env vars during the execution instead. It meanage the bundle of env vars plus
the execution
]
~SubStep1: [virtualEnv:  ]
-sourcing execution result:
start of source
end of source

-Step2:
cmd( 1):
-
starting the main

-
 .. ok
cmd( 2):
-
AAA = sourced_aaa
BBB = sourced_bbb


-
 .. ok
. ok
```

**Comment by fentas** [comment]
I outsource personal/sensitive information into a separate file `.env.secret`
This file is excluded by `.gitignore`
Within the `.envrc` I check if this file exists, parse and source it.
Sometime I create a `.env.secret.template` which holds default values.
This file will be copied to `.env.secret` if this does not exist.

```bash
copy::template() {
  local -r file="${PATH_BASE}/${1}"
  [ -f "${file}" ] ||
    cp "${file}.template" "${file}"
}

env::export() {
  local env="${PATH_BASE}/${1}"
  # shellcheck disable=SC2046
  [ ! -f "${env}" ] || {
    export $(grep -v '^#' "${env}" | sed -E 's/\s+=\s+/=/g' | xargs -d '\n')

    ! command -v watch_file &>/dev/null ||
      watch_file "${env}"
  }
}

copy::template ".env.secret"
env::export ".env.secret"

**Comment by stephencheng** [comment]
> ```shell
> copy::template()
> ```

 interesting, what is this syntax? bash/zsh function?

FYI: There is a way to handle secure env var: https://upcmd.netlify.app/security/c0197/, or check out the chapter of security

**Comment by Nadrieril** [comment]
I just realized there's an easy workaround for this: I can put the repo I'm interested in into a folder that contains the `.envrc` :D
```
some_folder/
  .envrc
  shell.nix
  the_actual_repo/
```

**Comment by oryband** [comment]
FYI the code section in this reply will not work on Mac OSX since `xargs -d` isn't available. Replace that line with:

```bash
    export $(grep -v '^#' "${env}" | sed -E 's/\s+=\s+/=/g' | tr '\n' '\0')
```
