### ISSUE TITLE
Messages show terminal control codes even when not connected to a terminal

### ISSUE THREAD

**Issue by tudortimi** [direnv/direnv#994]
I'm running `direnv exec some_script` from within a Jenkins pipeline. The pipeline logs show the following:

```
[mdirenv: loading ~/jenkins_slave/<long-path>/.envrc
```

Note the `[m` at the beginning of the message. I'm guessing this is a terminal control code.

I'm not sure how this could be easily reproduced. I tried redirecting stdout/stderr to a file, hoping to see the control code in the log file, but I can't seem to be able to do it. Since the output file is not a terminal, this would have been a way to check the fix.

Since Jenkins logs (and logs in general) don't support terminal control codes, they shouldn't be printed.

**Environment**
 - OS: RHEL7
 - Shell: sh (started from bash 4.4.20)
 - Direnv version 2.32.1

**Comment by tudortimi** [comment]
`sh` is usually `bash` started as `sh`, i.e. the `sh` executable is a link to the `bash` executable.

**Comment by doolio** [comment]
OK, but not the case for me.

**Comment by 0verbyte** [comment]
What is the TERM set to in that pipeline environment (`echo $TERM`)? Can you try exporting the environment variable`TERM=dumb` before running `direnv exec <script>` to see if the color code shows up still.

**Comment by tudortimi** [comment]
I echoed the variable and it seems that `TERM` is already set to `dumb` in Jenkins.

**Comment by zimbatm** [comment]
direnv checks if stderr is a tty. Something like this should fix it: `direnv exec some_script 2> >(cat >&2);`

**Comment by tudortimi** [comment]
@zimbatm So the main point is that the Jenkins console actually is a terminal. I was wrongly equating "terminal" with "shell".

I read up a bit on the topic of terminals. I see that it's possible to query whether the terminal supports colors: https://unix.stackexchange.com/questions/9957/how-to-check-if-bash-can-print-colors. I'll execute `tput colors` in Jenkins to see what it returns (hopefully 2).

I'm guessing direnv doesn't check the number of colors that are supported, right?

**Comment by tudortimi** [comment]
I did a couple of things in the Jenkins pipeline:

```
#!/bin/bash
                
echo $TERM
echo `tput -T dumb colors`
echo `tput colors`
test -t 2 && echo "stderr is a tty"
test -t 2 || echo "stderr is not a tty"
```

I got the following:

![image](https://user-images.githubusercontent.com/8170909/203829242-a059506c-ae20-4f0f-9704-026a93649c08.png)

It seems that stderr is not a tty.

**Comment by tudortimi** [comment]
I also tried the suggested redirect (`2> >(cat >&2)`), but I'm still getting the control characters:

![image](https://user-images.githubusercontent.com/8170909/203829948-a0f1b566-6871-4d69-bd83-3b5df29e9165.png)

**Comment by 0verbyte** [comment]
Interesting. I'm still new to this project, but it looks like the escape is being added from this function. 

https://github.com/direnv/direnv/blob/c362809a933f9fafe3081f96c291737248634559/stdlib.sh#L135-L144

**Comment by zimbatm** [comment]
^ yes that's the logic. I'm assuming that if the console is a tty it will also support control characters.

**Comment by tudortimi** [comment]
Mystery solved, the `-t 2` test isn't yet present in version 2.32.1.

**Comment by tudortimi** [comment]
Are you planning on releasing a 2.32.2 soon?

**Comment by zimbatm** [comment]
It's been a while isn't it? Released v2.32.2: https://github.com/direnv/direnv/releases/tag/v2.32.2

**Comment by tudortimi** [comment]
Works like a charm. Thanks for releasing.
